### ISSUE TITLE
Usar pip para instalar dependencias

### ISSUE THREAD

**Issue by cloudson** [vmeazevedo/Previsao_do_Tempo-v1.0#2]
Posso estar errado mas no README você diz
> Instalação das bibliotecas (caso não as tenha): request + json + pprint

Sempre que criamos um projeto que depende de outras bibliotecas podemos (e muitas vezes devemos) usar o conceito de gerenciador de dependencias. Eu expliquei um pouco sobre esse conceito [nesse video](https://youtu.be/8XOkbHeFsv4), basicamente o que você vai fazer é declarar um arquivo chamado `requirements.txt` e nele voce vai dizer quais as bibliotecas que seu projeto precisa. Quem baixar seu projeto vai correr um comando `pip install` e automaticamente baixar as dependencias.

**Comment by cloudson** [comment]
Pra deixar claro, somente bibliotecas externas, que não com a própria linguagem.

**Comment by vmeazevedo** [comment]
Perfeito. Era basicamente isso o que eu queria dizer no README, não conhecia esse conceito do requirements.txt, irei atualizar o projeto com esse ponto e corrigir o README. Muito obrigado pelo Feedback!
