### ISSUE TITLE
Use tags ou releseas no github para fazer versões

### ISSUE THREAD

**Issue by cloudson** [vmeazevedo/Previsao_do_Tempo-v1.0#3]
Isso é só um detalhe, geralmente o mesmo projeto vai evoluindo e você vai lançando versões diferentes que são encontradas aqui 
https://github.com/vmeazevedo/Previsao_do_Tempo-v1.0/releases

você não precisa duplicar o código ou criar repositórios diferentes ;) 
Mas se seu objetivo era manter as duas versões pras pessoas lerem os codigos mais facilmente, não há problema nenhum com isso.

**Comment by vmeazevedo** [comment]
Cara maravilha! Basicamente era o que eu gostaria de fazer, porém como eu lhe disse ainda estou aprendendo e não conhecia ainda o termo, então esses feedbacks estão me ensinando muito! Acabei de soltar o release com a nova versão! Obrigado novamente cara!

**Comment by cloudson** [comment]
Fica tranquilo, é muita coisa ao mesmo tempo. Que bom que ajudei. 
Provavelmente você criou as releases pelo link que te dei mas quando tiver tempo, dá uma estudada no conceito de git tags, que foi o que o github fez por baixo dos panos 😉 .
